### ISSUE TITLE
Upgrade to mem>=4.x

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsjpyradia#7]
There's a vulnerability (according to GitHub scan).

**Comment by mkeilman** [comment]
BTW my "security" tab lists nothing.  How can I check for these?

**Comment by robnagler** [comment]
I have no idea. Mine's empty too. I get a "weekly summary" email. Maybe update notification preferences?

![Screen Shot 2019-11-05 at 5 23 37 PM](https://user-images.githubusercontent.com/5495179/68257594-0e157800-fff1-11e9-8084-885a9c133b0f.png)
